### ISSUE TITLE
Support for Unit-Subqueries in top level call?

### ISSUE THREAD

**Issue by michael-simons** [neo4j-contrib/cypher-dsl#533]
Unsure if I want to support this https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/#subquery-unit and if this is often used at all…

**Comment by Andy2003** [comment]
If it helps you decide: for neo4j-graphql-java, the unit-subqueries would help us, since then I don't have to think up fun names for the return value that don't conflict in the parent context. Above all, I don't have to use unnecessary count queries.

For example take a look at this query (from the js lib):

https://github.com/neo4j/graphql/blob/dev/packages/graphql/tests/tck/operations/create.test.ts#L158

```cypher
UNWIND $create_param0 AS create_var0
CALL {
    WITH create_var0
    CREATE (create_this1:Movie)
    SET
        create_this1.id = create_var0.id
    WITH create_this1, create_var0
    CALL {
        WITH create_this1, create_var0
        UNWIND create_var0.actors.create AS create_var2
        WITH create_var2.node AS create_var3, create_var2.edge AS create_var4, create_this1
        CREATE (create_this5:Actor)
        SET
            create_this5.name = create_var3.name
        MERGE (create_this1)<-[create_this6:ACTED_IN]-(create_this5)
        RETURN collect(NULL) AS create_var7
    }
    RETURN create_this1
}
RETURN collect(create_this1 { .id }) AS data
```

We could get rid of `RETURN collect(NULL) AS create_var7`

**Comment by ikwattro** [comment]
To give more use case when unit subqueries are used. It's just a joy for when you need to unwind multiple collections from the parameters and one of them can be null, we use it in most of our data pipelines.

```cypher
MATCH (n:Person)
CALL {
    WITH n
    UNWIND [] AS i
    SET n.unit1 = i
}
CALL {
    WITH n
    UNWIND [1,2,3] AS i
    SET n.unit2 = i
}
RETURN n
```

**Comment by michael-simons** [comment]
That should work with the latest main branch.
