### ISSUE TITLE
[Question] prevent procedure calls using the DSL parser

### ISSUE THREAD

**Issue by ClemDoum** [neo4j-contrib/cypher-dsl#758]
Hi, I'm current using the DSL parser to validate queries from users.

Is there any way to prevent procedure calls (I couldn't find anything in the [doc]()https://neo4j-contrib.github.io/cypher-dsl)? 
Can this be done using the `Statement.getCatalog()` ?
If so, is there any other way ( I'm currently using `2022.8.5` because I still need to stick to JDK 11 for a small while) ?

Thank you for your help !
Clément

**Comment by michael-simons** [comment]
Hi @ClemDoum sorry for the late reply due to vacation.

- The catalog is not in 2022.8.5
- Not yet possible in general

I could add a callback to catch the parsing of procedure calls and I am open to backport it to 2022.8.5.

**Comment by michael-simons** [comment]
Just merged into main, and a newly created 2022.9 (due to semver requirements, but it's essentially 2022.8.6), example how to use this is here

https://github.com/neo4j-contrib/cypher-dsl/blob/e9f6482d2795d313d7204ffcefa26720162e5c94/neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java#L613

2022.9.0 will go out later today.

Please let us know if this works for you @ClemDoum

**Comment by ClemDoum** [comment]
It's perfect, thanks a lot for backporting it, it will be very useful thanks a lot !

**Comment by michael-simons** [comment]
Awesome, glad to hear!
