### ISSUE TITLE
Bug at ListLiteral at toString method

### ISSUE THREAD

**Issue by lena-precog** [neo4j-contrib/cypher-dsl#78]
getContent() return provided type and not literal so toString() method failed with cast exception

**Comment by meistermeier** [comment]
Could you please provide more content? I tried to reproduce it but maybe got your comment wrong because it is working the way I tried it. This is the output of a `ListLiteral#getContent` with a `StringLiteral` and a `NumberLiteral` provided: `[org.neo4j.cypherdsl.core.StringLiteral@6dc17b83, org.neo4j.cypherdsl.core.NumberLiteral@5e0826e7]`

**Comment by lena-precog** [comment]
not a bug.i provided list of string instead list of literal

**Comment by michael-simons** [comment]
Thanks, Lena!
